services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - TEST_RUN= TRUE
      - RUN_ID=Test123
      - AWS_DEFAULT_REGION=eu-north-1
      - MODEL_LOCATION=/app/model
      - SCALER_LOCATION=/app/preprocessor
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    volumes:
      - "./models_mlflow:/app/model"
      - "./preprocessor:/app/preprocessor"
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis