source_stream_name = "prod_insurance_events_r"
output_stream_name = "prod_insurance_predictions_r"
model_bucket = "prod-mlflow-models-code-owners-r"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "prod_stream_insurance_price_r"
lambda_function_name = "prod_prediction_lambda_r"
