triggers:
- description: null
  envs: []
  last_enabled_at: 2024-10-20 14:30:40.720290+00:00
  name: Retraining model hourly m
  pipeline_uuid: automatic_retraining_mp
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-10-20 14:29:00+00:00
  status: active
  token: 8699edbda5484ceea2d01ed655a9e571
  variables: {}
