emr_config: null
features:
  override: false
features_defined:
  add_new_block_v2: true
  command_center: true
  compute_management: false
  custom_design: true
  data_integration_in_batch_pipeline: true
  dbt_v2: true
  display_local_timezone: true
  global_hooks: true
  interactions: true
  notebook_block_output_split_view: true
  operation_history: true
  polars: true
features_override: {}
help_improve_mage: true
latest_version: 0.9.74
name: Learning_Data_Preparation_1
openai_api_key: null
pipelines: null
platform_settings:
  projects:
    Learning_Data_Preparation_1:
      path: Learning_Data_Preparation_1
    falling_flower: {}
    heroic_glacier: {}
    sparkling_artificer: {}
    unit_0_setup: {}
    unit_1_data_preparation: {}
    unit_2_training: {}
    unit_3_observability: {}
project_uuid: 1458cb2e4b3f41999ead3ff9ba76b3b3
projects:
  Learning_Data_Preparation_1:
    path: Learning_Data_Preparation_1
  medical_insurance_price:
    path: medical_insurance_price
  unit_0_setup: {}
  unit_1_data_preparation: {}
  unit_2_training: {}
  unit_3_observability: {}
remote_variables_dir: null
repo_path: /home/src/mlops/Learning_Data_Preparation_1
root_project: false
settings:
  active: true
  path: Learning_Data_Preparation_1
  uuid: Learning_Data_Preparation_1
spark_config: null
version: 0.9.73
workspace_config_defaults: {}
